In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Admission_Prediction.csv')
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [3]:
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0           1      337.0        118.0                4.0  4.5  4.5  9.65   
1           2      324.0        107.0                4.0  4.0  4.5  8.87   
2           3        NaN        104.0                3.0  3.0  3.5  8.00   
3           4      322.0        110.0                3.0  3.5  2.5  8.67   
4           5      314.0        103.0                2.0  2.0  3.0  8.21   

   Research  Chance of Admit  
0         1             0.92  
1         1             0.76  
2         1             0.72  
3         1             0.80  
4         0             0.65

In [4]:
df.dtypes

Serial No.             int64
GRE Score            float64
TOEFL Score          float64
University Rating    float64
SOP                  float64
LOR                  float64
CGPA                 float64
Research               int64
Chance of Admit      float64
dtype: object

In [5]:
from sklearn.linear_model import LinearRegression,Ridge,RidgeCV,ElasticNet,ElasticNetCV,Lasso,LassoCV

In [6]:
df.drop(columns=['Serial No.'],inplace=True)

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [8]:
df['GRE Score'] =le.fit_transform(df['GRE Score'])
df['TOEFL Score'] =le.fit_transform(df['TOEFL Score'])
df['University Rating'] =le.fit_transform(df['University Rating'])

In [9]:
df.shape

(500, 8)

In [10]:
df.isnull().sum()

GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [11]:
X=df.drop(['Chance of Admit'], axis=1)
y=df['Chance of Admit']

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.30, random_state = 42)

In [13]:
lr = LinearRegression()

In [14]:
lr.fit(X_train,y_train)

LinearRegression()

In [15]:
lr.predict(X_test)

array([0.91589462, 0.8053396 , 0.55857811, 0.74719106, 0.81781667,
       0.85781524, 0.49166938, 0.70935258, 0.83145831, 0.80841409,
       0.71334306, 0.73041612, 0.6414152 , 0.92360151, 0.82934807,
       0.51791402, 0.82537646, 0.60336387, 0.54393378, 0.57543592,
       0.66371722, 0.55677105, 0.72321429, 0.78343807, 0.77571008,
       0.61845154, 0.95355824, 0.84209465, 0.62275706, 0.74922094,
       0.56199222, 0.73430738, 0.55015005, 0.86487906, 0.67232117,
       0.73420753, 0.55819503, 0.96834873, 0.65223304, 0.7129267 ,
       0.95642627, 0.57626183, 0.74841088, 0.85470014, 0.93155595,
       0.5878851 , 0.9547599 , 0.83159317, 0.84009579, 0.92845884,
       0.89433666, 0.60989517, 0.71467287, 0.51294122, 0.94801259,
       0.57373348, 0.95451609, 0.74264186, 0.67940854, 0.50673553,
       0.64727007, 0.68113055, 0.60362143, 0.59532999, 0.43983593,
       0.58484393, 0.8694265 , 0.8939744 , 0.65734591, 0.70354984,
       0.61987462, 0.77886291, 0.67910176, 0.55724761, 0.55912

In [16]:
lr.coef_

array([0.00106632, 0.00405121, 0.00340388, 0.00184074, 0.01255936,
       0.12803799, 0.02745271])

In [17]:
lr.intercept_

-0.5365873765978244

In [18]:
lr.score(X_test,y_test)

0.8205760685115967

In [19]:
las = LassoCV(alphas=None,cv=100,max_iter=1000,normalize=True)

In [20]:
las.fit(X_train,y_train)

LassoCV(cv=100, normalize=True)

In [21]:
las.alpha_

6.546733501959499e-06

In [22]:
las.score(X_test,y_test)

0.8205798679011874

In [23]:
els = ElasticNetCV(alphas=None,cv=10)

In [24]:
els.fit(X_train,y_train)

ElasticNetCV(cv=10)

In [25]:
els.alpha_

0.0024101311020408166

In [26]:
els.predict(X_test)

array([0.91289393, 0.79776401, 0.56888155, 0.7577424 , 0.81528575,
       0.85458082, 0.49269878, 0.72091696, 0.82302719, 0.80539301,
       0.71853886, 0.73191614, 0.64476684, 0.92347292, 0.8235676 ,
       0.51679901, 0.82436891, 0.59554106, 0.54443805, 0.57204177,
       0.66063352, 0.55756726, 0.71629458, 0.78281982, 0.77669517,
       0.6126814 , 0.95068713, 0.83935538, 0.62729126, 0.74465382,
       0.56418553, 0.73672718, 0.55563687, 0.85997551, 0.68245192,
       0.73266795, 0.55656588, 0.96793136, 0.64752826, 0.71054626,
       0.95250363, 0.57108851, 0.75083302, 0.85271681, 0.92927737,
       0.58572807, 0.95250923, 0.82969652, 0.84471805, 0.9242546 ,
       0.88629763, 0.6251635 , 0.71218381, 0.51597523, 0.94674095,
       0.58509195, 0.95051171, 0.7450871 , 0.67526358, 0.50282014,
       0.63697696, 0.67519415, 0.60375978, 0.6003484 , 0.44091995,
       0.59398872, 0.86494368, 0.89085794, 0.65796177, 0.70486265,
       0.61457532, 0.7784931 , 0.67959016, 0.56498604, 0.55741

In [27]:
els.l1_ratio

0.5

In [28]:
els.score(X_test,y_test)

0.8170050201414701

In [29]:
ridge=RidgeCV(alphas=np.random.uniform(0,10,50),cv=10,normalize=True)

In [30]:
ridge.fit(X_train,y_train)

RidgeCV(alphas=array([0.64879012, 5.33593681, 6.88098872, 9.29346347, 4.23086878,
       9.43194036, 8.0550689 , 2.35033056, 9.19018996, 6.90292287,
       4.35916978, 9.68734292, 1.72213636, 9.36282022, 5.58589723,
       5.39844408, 8.25412912, 4.65418654, 5.66064575, 3.63463932,
       6.62290694, 1.82070504, 5.91349173, 3.13499767, 5.00980332,
       2.08879708, 8.73579162, 3.55934475, 3.27491066, 4.84923317,
       7.64623064, 4.3652301 , 7.84919234, 7.57230765, 9.403673  ,
       0.23680307, 0.19883973, 4.52232702, 1.76716011, 9.02745612,
       7.05329239, 4.33009656, 6.16956204, 5.81844327, 7.70491327,
       8.14249146, 0.75553144, 0.78600655, 1.81544223, 6.50582093]),
        cv=10, normalize=True)

In [31]:
ridge.score(X_test,y_test)

0.8133294773639459

In [32]:
ridge.coef_

array([0.00173056, 0.00414726, 0.00619386, 0.0100884 , 0.01470052,
       0.08455861, 0.02834478])

In [33]:
ridge.alpha_

0.19883972714855092

In [34]:
ridge.intercept_

-0.22393027160316126

In [35]:
import pickle

In [36]:
lr.predict([[337.0,107.0,3.0,4.0,4.5,8.00,1]])

array([1.38209001])

In [37]:
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit, Length: 500, dtype: float64